name: Test
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repos
        uses: actions/checkout@v2
      - name: Set php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer pecl
          extensions: event
      - name: Install deps
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repos
        uses: actions/checkout@v2
      - name: Set PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install deps
        run: composer install
      - name: Run linter
        run: vendor/bin/phpcs

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repos
        uses: actions/checkout@v2
      - name: Set PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install deps
        run: composer install
      - name: Run psalm
        run: vendor/bin/psalm
